# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    schoolfinderform.class: AppBundle\Helpers\FindSchoolForm
    dataconverter.class: AppBundle\Helpers\DataConverter
    excel_iofactory.class: PHPExcel\PHPExcel\PHPExcel_IOFactory
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    school_finder:
        class: %schoolfinderform.class%
        arguments: 
                - "@doctrine.orm.entity_manager"
                - "@form.factory"
                - "@request_stack"
    data_converter:
        class: %dataconverter.class%
        arguments:
                - "@doctrine.dbal.default_connection"
    app_bundle.button_type_extension:
        class: AppBundle\Form\Extension\ButtonTypeExtension
        tags:
            - { name: form.type_extension, alias: button }
    app.form.change_password:
        class: AppBundle\Form\Type\ChangePasswordFormType
        tags:
            - { name: form.type, alias: app_user_change_password }